### ISSUE TITLE
Why has this package a dependency on flutter?

### ISSUE THREAD

**Issue by HerrNiklasRaab** [jonsamwell/flutter_simple_dependency_injection#10]
Hi @jonsamwell,

why does this package depend on flutter, can we kill this dependency?
Because now we are going to remove the flutter dependency from our business logic package.

Best wishes,

Niklas

**Comment by jonsamwell** [comment]
Hi @HerrNiklasRaab yes I agree I see no reason for this to depend on Flutter.  Not sure how I would go about changing the name of the library though?

**Comment by HerrNiklasRaab** [comment]
Hi @jonsamwell ,

great news, let's try this one:

```yaml
name: flutter_simple_dependency_injection
description: A super simple dependency injection implementation for flutter that behaviours like any normal IOC container and does not rely on mirrors
version: 0.0.5
author: Jon Samwell <jonsamwell@gmail.com>
homepage: https://github.com/jonsamwell/flutter_simple_dependency_injection

dependencies:

dev_dependencies:
  test: any

environment:
  sdk: ">=2.0.0-dev.35 <3.0.0"
```

Hope this works,

Niklas
